#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=20

TARGET=""
CHECK_ONLY=0
ENV_FILE="${XDG_CONFIG_HOME:-${HOME}/.config}/danbao-openwrt/setup.env"
SSH_OPTIONS=(-o ConnectTimeout=8 -o ServerAliveInterval=10 -o ServerAliveCountMax=3)

usage() {
  printf 'Usage: %s [--target root@HOST] [--check] [--env-file PATH]\n' "$0"
}

while (($#)); do
  case "$1" in
    --target)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      TARGET="$2"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    --env-file)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      ENV_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$1" >&2
    exit 1
  }
}

validate_target() {
  [[ "$1" =~ ^root@[A-Za-z0-9._:-]+$ ]] || {
    warn "target must look like root@192.168.1.1 or root@router.example"
    return 1
  }
}

validate_ipv4() {
  local ip="$1" part
  [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  IFS=. read -r -a parts <<<"$ip"
  for part in "${parts[@]}"; do
    ((10#$part >= 0 && 10#$part <= 255)) || return 1
  done
}

validate_netmask() {
  case "$1" in
    255.255.255.0|255.255.0.0|255.0.0.0|255.255.255.128|255.255.255.192|255.255.255.224|255.255.255.240|255.255.255.248|255.255.255.252) return 0 ;;
    *) return 1 ;;
  esac
}

validate_cidr() {
  local address="${1%/*}" prefix="${1##*/}"
  validate_ipv4 "$address" && [[ "$prefix" =~ ^[0-9]+$ ]] && ((prefix >= 8 && prefix <= 30))
}

validate_hostname() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9.-]{0,62}$ ]]
}

router_host() {
  printf '%s' "${TARGET#root@}"
}

ssh_router() {
  ssh "${SSH_OPTIONS[@]}" "$TARGET" "$@"
}

wait_for_ssh() {
  local attempts=0
  until ssh_router true >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    ((attempts < 30)) || return 1
    sleep 2
  done
}

verify_router() {
  ssh_router 'set -eu
    echo "release=$(sed -n "s/^DISTRIB_RELEASE=//p" /etc/openwrt_release | tr -d "\047")"
    echo "lan=$(uci -q get network.lan.ipaddr || true)"
    echo "daed=$(pidof daed >/dev/null && echo running || echo stopped)"
    echo "tailscale=$(tailscale status --json >/dev/null 2>&1 && echo running || echo stopped)"
    echo "vnstat=$(pidof vnstatd >/dev/null && echo running || echo stopped)"
    tailscale status 2>/dev/null | sed -n "1,6p" || true
    sysupgrade -l 2>/dev/null | grep -E "^/etc/(daed/wing.db|tailscale/|vnstat/)" || true'
}

for command in ssh curl jq tar; do
  require_command "$command"
done

if [[ -z "$TARGET" ]]; then
  TARGET=$(_existing TARGET || true)
fi
TARGET="${TARGET:-root@192.168.1.1}"
validate_target "$TARGET" || exit 2

if ((CHECK_ONLY)); then
  verify_router
  exit 0
fi

banner "Portable ImmortalWrt bypass-router setup"

stage "Preflight and rollback backup" 2
ask TARGET "Router SSH target:"
validate_target "$TARGET" || exit 2
write_env TARGET "$TARGET"
say "Checking the signed firmware package baseline before touching configuration."
ssh_router 'set -eu
  for package in daed daed-geoip daed-geosite luci-app-daed luci-i18n-daed-zh-cn \
    tailscale luci-app-tailscale-community luci-i18n-tailscale-community-zh-cn \
    vnstat2 vnstati2 luci-app-vnstat2 luci-i18n-vnstat2-zh-cn open-vm-tools; do
    apk info -e "$package" >/dev/null || { echo "missing firmware package: $package" >&2; exit 1; }
  done'
backup_path=$(ssh_router 'set -eu
  stamp=$(date +%Y%m%d-%H%M%S)
  path="/root/openwrt-setup-backup-${stamp}.tar.gz"
  set -- /etc/config
  for candidate in /etc/daed/wing.db /etc/tailscale /etc/dropbear /etc/sysupgrade.conf /etc/vnstat.conf /etc/vnstat; do
    [ ! -e "$candidate" ] || set -- "$@" "$candidate"
  done
  tar -czf "$path" "$@"
  chmod 600 "$path"
  test -s "$path"
  printf "%s" "$path"')
note "rollback backup stored only on the router: $backup_path"

stage "LAN identity and reconnect" 3
ask LAN_IP "Static LAN IPv4 address:"
validate_ipv4 "$LAN_IP" || { warn "invalid IPv4 address"; exit 2; }
ask LAN_NETMASK "LAN netmask (for example 255.255.255.0):"
validate_netmask "$LAN_NETMASK" || { warn "unsupported netmask"; exit 2; }
ask LAN_GATEWAY "Main-router IPv4 gateway:"
validate_ipv4 "$LAN_GATEWAY" || { warn "invalid gateway"; exit 2; }
ask LAN_DNS "DNS server IPv4 address:"
validate_ipv4 "$LAN_DNS" || { warn "invalid DNS address"; exit 2; }
ask LAN_SUBNET "Advertised LAN CIDR (for example 10.10.0.0/24):"
validate_cidr "$LAN_SUBNET" || { warn "invalid LAN CIDR"; exit 2; }
ask ROUTER_HOSTNAME "Router hostname:"
validate_hostname "$ROUTER_HOSTNAME" || { warn "invalid hostname"; exit 2; }
for key in LAN_IP LAN_NETMASK LAN_GATEWAY LAN_DNS LAN_SUBNET ROUTER_HOSTNAME; do
  write_env "$key" "${!key}"
done
if confirm "Apply the network settings and reconnect to root@${LAN_IP}?"; then
  ssh_router sh -s -- "$LAN_IP" "$LAN_NETMASK" "$LAN_GATEWAY" "$LAN_DNS" "$ROUTER_HOSTNAME" <<'ROUTER_NETWORK'
set -eu
lan_ip="$1"; netmask="$2"; gateway="$3"; dns="$4"; hostname="$5"
uci set network.lan.proto='static'
uci set network.lan.ipaddr="$lan_ip"
uci set network.lan.netmask="$netmask"
uci set network.lan.gateway="$gateway"
uci -q delete network.lan.dns
uci add_list network.lan.dns="$dns"
uci set network.lan.delegate='0'
uci set dhcp.lan.ignore='1'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set system.@system[0].hostname="$hostname"
uci commit network
uci commit dhcp
uci commit system
(sleep 2; /etc/init.d/network restart) >/dev/null 2>&1 &
ROUTER_NETWORK
  TARGET="root@${LAN_IP}"
  write_env TARGET "$TARGET"
  wait_for_ssh || { warn "router did not return on ${LAN_IP}"; exit 1; }
else
  warn "network stage skipped"
fi

stage "SSH key and LAN-only password recovery" 2
ask SSH_PUBLIC_KEY "Path to the SSH public key:"
SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY/#\~/$HOME}"
[[ -f "$SSH_PUBLIC_KEY" ]] || { warn "public key not found: $SSH_PUBLIC_KEY"; exit 1; }
write_env SSH_PUBLIC_KEY "$SSH_PUBLIC_KEY"
public_key=$(<"$SSH_PUBLIC_KEY")
ssh_router sh -s -- "$public_key" <<'ROUTER_SSH'
set -eu
public_key="$1"
mkdir -p /etc/dropbear
touch /etc/dropbear/authorized_keys
chmod 700 /etc/dropbear
chmod 600 /etc/dropbear/authorized_keys
grep -qxF "$public_key" /etc/dropbear/authorized_keys || printf '%s\n' "$public_key" >> /etc/dropbear/authorized_keys
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].DirectInterface='lan'
uci commit dropbear
/etc/init.d/dropbear restart
ROUTER_SSH
if confirm "Set or rotate the root recovery password now?"; then
  ssh -t "${SSH_OPTIONS[@]}" "$TARGET" passwd
fi

stage "Services and persistent traffic history" 2
ssh_router 'set -eu
  mkdir -p /etc/vnstat /etc/openwrt-setup/migrations
  if [ -f /var/lib/vnstat/vnstat.db ] && [ ! -f /etc/vnstat/vnstat.db ]; then
    /etc/init.d/vnstat stop || true
    cp -p /var/lib/vnstat/vnstat.db /etc/vnstat/vnstat.db
  fi
  grep -q "^DatabaseDir \"/etc/vnstat\"" /etc/vnstat.conf || printf "\nDatabaseDir \"/etc/vnstat\"\n" >> /etc/vnstat.conf
  grep -q "^SaveInterval " /etc/vnstat.conf || printf "SaveInterval 5\n" >> /etc/vnstat.conf
  for path in /etc/daed/wing.db /etc/tailscale/ /etc/vnstat/ /etc/openwrt-setup/; do
    grep -qxF "$path" /etc/sysupgrade.conf || printf "%s\n" "$path" >> /etc/sysupgrade.conf
  done
  /etc/init.d/vnstat enable
  /etc/init.d/vnstat restart
  /etc/init.d/vmtoolsd enable
  /etc/init.d/vmtoolsd restart || true
  uci -q delete firewall.tailscale.network || true
  uci set firewall.tailscale.device="tailscale0"
  uci commit firewall
  if [ "$(uci -q get network.tailscale.proto || true)" = "none" ] && [ "$(uci -q get network.tailscale.device || true)" = "tailscale0" ]; then
    uci -q delete network.tailscale
    uci commit network
  fi
  /etc/init.d/firewall restart'

stage "daed private bootstrap and portable policy" 5
ask DAED_USERNAME "daed administrator username:"
ask_secret DAED_PASSWORD "daed administrator password:"
ask_secret DAED_SUBSCRIPTION "Node subscription URI:"
[[ -n "$DAED_USERNAME" && -n "$DAED_PASSWORD" && -n "$DAED_SUBSCRIPTION" ]] || {
  warn "daed username, password and subscription are required"
  exit 2
}
ssh_router 'uci set daed.config.enabled="1"; uci set daed.config.listen_addr="0.0.0.0:2023"; uci set daed.config.log_maxbackups="1"; uci set daed.config.log_maxsize="5"; uci commit daed; /etc/init.d/daed enable; /etc/init.d/daed restart'
DAED_ENDPOINT="http://$(router_host):2023/graphql"
for _ in {1..20}; do
  printf '%s' '{"query":"query { numberUsers }"}' | \
    curl -fsS --connect-timeout 2 -H 'Content-Type: application/json' --data-binary @- "$DAED_ENDPOINT" >/dev/null 2>&1 && break
  sleep 1
done

graphql() {
  local payload="$1"
  shift
  printf '%s' "$payload" | curl -fsS -H 'Content-Type: application/json' "$@" --data-binary @- "$DAED_ENDPOINT"
}

number_users=$(graphql "$(jq -cn '{query:"query { numberUsers }"}')" | jq -er '.data.numberUsers')
if [[ "$number_users" == "0" ]]; then
  auth_payload=$(jq -cn --arg u "$DAED_USERNAME" --arg p "$DAED_PASSWORD" '{query:"mutation($u:String!,$p:String!){createUser(username:$u,password:$p)}",variables:{u:$u,p:$p}}')
  DAED_TOKEN=$(graphql "$auth_payload" | jq -er '.data.createUser')
else
  auth_payload=$(jq -cn --arg u "$DAED_USERNAME" --arg p "$DAED_PASSWORD" '{query:"query($u:String!,$p:String!){token(username:$u,password:$p)}",variables:{u:$u,p:$p}}')
  DAED_TOKEN=$(graphql "$auth_payload" | jq -er '.data.token')
fi
AUTH_HEADER=(-H "Authorization: Bearer ${DAED_TOKEN}")

daed_backup=$(ssh_router 'set -eu; stamp=$(date +%Y%m%d-%H%M%S); path="/etc/daed/wing.db.setup-${stamp}"; cp -p /etc/daed/wing.db "$path"; chmod 600 "$path"; printf "%s" "$path"')

DAED_GLOBAL=$(jq -cn '{logLevel:"warn",tcpCheckUrl:["http://cp.cloudflare.com","1.1.1.1"],tcpCheckHttpMethod:"HEAD",udpCheckDns:["dns.google:53","8.8.8.8"],checkInterval:"30s",checkTolerance:"50ms",lanInterface:["br-lan"],wanInterface:["auto"],allowInsecure:false,dialMode:"domain",disableWaitingNetwork:false,enableLocalTcpFastRedirect:false,autoConfigKernelParameter:true,autoConfigFirewallRule:false,sniffingTimeout:"100ms",tlsImplementation:"tls",utlsImitate:"chrome_auto",tlsFragment:false,pprofPort:0,mptcp:false,fallbackResolver:"8.8.8.8:53"}')
DAED_DNS=$(cat <<'DAED_DNS_EOF'
ipversion_prefer: 4
upstream {
  alidns: 'udp://223.5.5.5:53'
  googledns: 'tcp+udp://8.8.8.8:53'
}
routing {
  request {
    qtype(https) -> reject
    qname(suffix: openai.com, suffix: chatgpt.com, suffix: oaistatic.com, suffix: oaiusercontent.com, suffix: anthropic.com, suffix: claude.ai, suffix: perplexity.ai, suffix: x.ai, suffix: grok.com, suffix: gemini.google.com, suffix: generativelanguage.googleapis.com, suffix: ai.google.dev, suffix: makersuite.google.com, suffix: copilot.microsoft.com, suffix: githubcopilot.com) -> googledns
    qname(geosite:category-ai-!cn) -> googledns
    qname(geosite:cn) -> alidns
    fallback: googledns
  }
  response {
    upstream(googledns) -> accept
    ip(geoip:private) && !qname(geosite:cn) -> googledns
    fallback: accept
  }
}
DAED_DNS_EOF
)
DAED_ROUTING=$(cat <<'DAED_ROUTING_EOF'
pname(NetworkManager, systemd-resolved, dnsmasq) -> must_direct
pname(tailscaled) -> must_direct
domain(suffix: tailscale.com) -> direct
l4proto(udp) && dport(3478) -> direct
l4proto(udp) && sport(41641) -> direct
dip(geoip:private) -> direct
domain(suffix: openai.com, suffix: chatgpt.com, suffix: oaistatic.com, suffix: oaiusercontent.com, suffix: anthropic.com, suffix: claude.ai, suffix: perplexity.ai, suffix: x.ai, suffix: grok.com, suffix: gemini.google.com, suffix: generativelanguage.googleapis.com, suffix: ai.google.dev, suffix: makersuite.google.com, suffix: copilot.microsoft.com, suffix: githubcopilot.com) -> ai
domain(geosite:category-ai-!cn) -> ai
dip(geoip:cn) -> direct
domain(geosite:cn) -> direct
fallback: proxy
DAED_ROUTING_EOF
)

configure_daed() {
  local state config_id dns_id routing_id subscription_id proxy_id ai_id response desired_nodes current_nodes add_nodes del_nodes
  state=$(graphql "$(jq -cn '{query:"query { configs(selected:true){id} dnss(selected:true){id} routings(selected:true){id} groups{id name nodes{id} subscriptions{id}} subscriptions{id tag nodes{edges{id name}}} }"}')" "${AUTH_HEADER[@]}") || return 1

  config_id=$(jq -r '.data.configs[0].id // empty' <<<"$state")
  if [[ -n "$config_id" ]]; then
    response=$(graphql "$(jq -cn --arg id "$config_id" --argjson global "$DAED_GLOBAL" '{query:"mutation($id:ID!,$global:globalInput!){updateConfig(id:$id,global:$global){id}}",variables:{id:$id,global:$global}}')" "${AUTH_HEADER[@]}") || return 1
    jq -e '.data.updateConfig.id and ((.errors // [])|length==0)' >/dev/null <<<"$response" || return 1
  else
    response=$(graphql "$(jq -cn --argjson global "$DAED_GLOBAL" '{query:"mutation($global:globalInput!){createConfig(name:\"portable\",global:$global){id}}",variables:{global:$global}}')" "${AUTH_HEADER[@]}") || return 1
    config_id=$(jq -er '.data.createConfig.id' <<<"$response") || return 1
    graphql "$(jq -cn --arg id "$config_id" '{query:"mutation($id:ID!){selectConfig(id:$id)}",variables:{id:$id}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi

  dns_id=$(jq -r '.data.dnss[0].id // empty' <<<"$state")
  if [[ -n "$dns_id" ]]; then
    response=$(graphql "$(jq -cn --arg id "$dns_id" --arg value "$DAED_DNS" '{query:"mutation($id:ID!,$value:String!){updateDns(id:$id,dns:$value){id}}",variables:{id:$id,value:$value}}')" "${AUTH_HEADER[@]}") || return 1
    jq -e '.data.updateDns.id and ((.errors // [])|length==0)' >/dev/null <<<"$response" || return 1
  else
    response=$(graphql "$(jq -cn --arg value "$DAED_DNS" '{query:"mutation($value:String!){createDns(name:\"portable\",dns:$value){id}}",variables:{value:$value}}')" "${AUTH_HEADER[@]}") || return 1
    dns_id=$(jq -er '.data.createDns.id' <<<"$response") || return 1
    graphql "$(jq -cn --arg id "$dns_id" '{query:"mutation($id:ID!){selectDns(id:$id)}",variables:{id:$id}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi

  routing_id=$(jq -r '.data.routings[0].id // empty' <<<"$state")
  if [[ -n "$routing_id" ]]; then
    response=$(graphql "$(jq -cn --arg id "$routing_id" --arg value "$DAED_ROUTING" '{query:"mutation($id:ID!,$value:String!){updateRouting(id:$id,routing:$value){id}}",variables:{id:$id,value:$value}}')" "${AUTH_HEADER[@]}") || return 1
    jq -e '.data.updateRouting.id and ((.errors // [])|length==0)' >/dev/null <<<"$response" || return 1
  else
    response=$(graphql "$(jq -cn --arg value "$DAED_ROUTING" '{query:"mutation($value:String!){createRouting(name:\"portable\",routing:$value){id}}",variables:{value:$value}}')" "${AUTH_HEADER[@]}") || return 1
    routing_id=$(jq -er '.data.createRouting.id' <<<"$response") || return 1
    graphql "$(jq -cn --arg id "$routing_id" '{query:"mutation($id:ID!){selectRouting(id:$id)}",variables:{id:$id}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi

  subscription_id=$(jq -r '.data.subscriptions[] | select(.tag=="portable-setup") | .id' <<<"$state" | head -n1)
  if [[ -n "$subscription_id" ]]; then
    graphql "$(jq -cn --arg id "$subscription_id" --arg link "$DAED_SUBSCRIPTION" '{query:"mutation($id:ID!,$link:String!){updateSubscriptionLink(id:$id,link:$link){id}}",variables:{id:$id,link:$link}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
    response=$(graphql "$(jq -cn --arg id "$subscription_id" '{query:"mutation($id:ID!){updateSubscription(id:$id){id}}",variables:{id:$id}}')" "${AUTH_HEADER[@]}") || return 1
  else
    response=$(graphql "$(jq -cn --arg link "$DAED_SUBSCRIPTION" '{query:"mutation($arg:ImportArgument!){importSubscription(rollbackError:true,arg:$arg){sub{id}}}",variables:{arg:{link:$link,tag:"portable-setup"}}}')" "${AUTH_HEADER[@]}") || return 1
    subscription_id=$(jq -er '.data.importSubscription.sub.id' <<<"$response") || return 1
  fi

  state=$(graphql "$(jq -cn '{query:"query { groups{id name nodes{id} subscriptions{id}} subscriptions{id tag nodes{edges{id name}}} }"}')" "${AUTH_HEADER[@]}") || return 1
  proxy_id=$(jq -r '.data.groups[] | select(.name=="proxy") | .id' <<<"$state" | head -n1)
  if [[ -z "$proxy_id" ]]; then
    response=$(graphql "$(jq -cn '{query:"mutation { createGroup(name:\"proxy\",policy:min_moving_avg){id}}"}')" "${AUTH_HEADER[@]}") || return 1
    proxy_id=$(jq -er '.data.createGroup.id' <<<"$response") || return 1
  fi
  if ! jq -e --arg gid "$proxy_id" --arg sid "$subscription_id" '.data.groups[] | select(.id==$gid) | any(.subscriptions[]; .id==$sid)' >/dev/null <<<"$state"; then
    graphql "$(jq -cn --arg id "$proxy_id" --arg sid "$subscription_id" '{query:"mutation($id:ID!,$subs:[ID!]!){groupAddSubscriptions(id:$id,subscriptionIDs:$subs)}",variables:{id:$id,subs:[$sid]}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi
  graphql "$(jq -cn --arg id "$proxy_id" '{query:"mutation($id:ID!){groupSetPolicy(id:$id,policy:min_moving_avg)}",variables:{id:$id}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1

  ai_id=$(jq -r '.data.groups[] | select(.name=="ai") | .id' <<<"$state" | head -n1)
  if [[ -z "$ai_id" ]]; then
    response=$(graphql "$(jq -cn '{query:"mutation { createGroup(name:\"ai\",policy:min_moving_avg){id}}"}')" "${AUTH_HEADER[@]}") || return 1
    ai_id=$(jq -er '.data.createGroup.id' <<<"$response") || return 1
    current_nodes='[]'
  else
    current_nodes=$(jq -c --arg id "$ai_id" '[.data.groups[] | select(.id==$id) | .nodes[].id]' <<<"$state")
  fi
  desired_nodes=$(jq -c --arg id "$subscription_id" '[.data.subscriptions[] | select(.id==$id) | .nodes.edges[] | select(.name|test("🇺🇸|美国|United States|USA|🇯🇵|日本|Japan";"i")) | .id] | unique' <<<"$state")
  [[ $(jq 'length' <<<"$desired_nodes") -gt 0 ]] || { warn "no Japan/US nodes found in subscription"; return 1; }
  add_nodes=$(jq -cn --argjson wanted "$desired_nodes" --argjson current "$current_nodes" '$wanted-$current')
  del_nodes=$(jq -cn --argjson wanted "$desired_nodes" --argjson current "$current_nodes" '$current-$wanted')
  if [[ $(jq 'length' <<<"$del_nodes") -gt 0 ]]; then
    graphql "$(jq -cn --arg id "$ai_id" --argjson nodes "$del_nodes" '{query:"mutation($id:ID!,$nodes:[ID!]!){groupDelNodes(id:$id,nodeIDs:$nodes)}",variables:{id:$id,nodes:$nodes}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi
  if [[ $(jq 'length' <<<"$add_nodes") -gt 0 ]]; then
    graphql "$(jq -cn --arg id "$ai_id" --argjson nodes "$add_nodes" '{query:"mutation($id:ID!,$nodes:[ID!]!){groupAddNodes(id:$id,nodeIDs:$nodes)}",variables:{id:$id,nodes:$nodes}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1
  fi
  graphql "$(jq -cn --arg id "$ai_id" '{query:"mutation($id:ID!){groupSetPolicy(id:$id,policy:min_moving_avg)}",variables:{id:$id}}')" "${AUTH_HEADER[@]}" >/dev/null || return 1

  response=$(graphql "$(jq -cn '{query:"mutation { run(dry:true) }"}')" "${AUTH_HEADER[@]}") || return 1
  jq -e '.data.run != null and ((.errors // [])|length==0)' >/dev/null <<<"$response" || return 1
  response=$(graphql "$(jq -cn '{query:"mutation { run(dry:false) }"}')" "${AUTH_HEADER[@]}") || return 1
  jq -e '.data.run != null and ((.errors // [])|length==0)' >/dev/null <<<"$response" || return 1
}

if ! configure_daed; then
  warn "daed configuration failed; restoring the pre-stage database"
  ssh_router sh -s -- "$daed_backup" <<'ROUTER_DAED_ROLLBACK'
set -eu
backup="$1"
/etc/init.d/daed stop || true
cp -p "$backup" /etc/daed/wing.db
/etc/init.d/daed restart
ROUTER_DAED_ROLLBACK
  exit 1
fi
note "daed dry-run and live reload succeeded"

stage "Tailscale login and subnet approval" 4
ssh_router sh -s -- "$LAN_SUBNET" <<'ROUTER_TAILSCALE'
set -eu
subnet="$1"
uci set tailscale.settings.accept_routes='0'
uci set tailscale.settings.advertise_exit_node='0'
uci set tailscale.settings.disable_magic_dns='1'
uci set tailscale.settings.ssh='0'
uci set tailscale.settings.advertise_routes="$subnet"
uci commit tailscale
/etc/init.d/tailscale enable
/etc/init.d/tailscale restart
if ! tailscale status --json 2>/dev/null | grep -q '"BackendState".*"Running"'; then
  : >/tmp/tailscale-login.log
  (tailscale up --accept-routes=false --accept-dns=false --ssh=false --advertise-routes="$subnet" > /tmp/tailscale-login.log 2>&1) &
else
  tailscale set --accept-routes=false --accept-dns=false --ssh=false --advertise-routes="$subnet"
fi
ROUTER_TAILSCALE
login_url=""
for _ in {1..20}; do
  login_log=$(ssh_router 'cat /tmp/tailscale-login.log 2>/dev/null || true')
  login_url=$(grep -Eo 'https://login\.tailscale\.com/a/[A-Za-z0-9_-]+' <<<"$login_log" | head -n1 || true)
  [[ -n "$login_url" ]] && break
  ssh_router 'tailscale status --json 2>/dev/null | grep -q '"'"'"BackendState".*"Running"'"'"'' && break
  sleep 1
done
if [[ -n "$login_url" ]]; then
  open_url "$login_url"
  pause "Complete Tailscale login in the browser, then press Enter."
fi
open_url "https://console.tailscale.com/admin/machines"
step "Approve the advertised route ${LAN_SUBNET} for this router."
pause "Route approved?"
open_url "https://console.tailscale.com/admin/acls/file"
step "Ensure your user has access to ${LAN_SUBNET}; do not restore a wildcard allow-all rule."
pause "Access policy updated?"

stage "End-to-end verification" 2
verify_router
ssh_router 'set -eu
  pidof daed >/dev/null
  pidof tailscaled >/dev/null
  pidof vnstatd >/dev/null
  test -f /etc/vnstat/vnstat.db
  tailscale netcheck 2>/dev/null | sed -n "1,18p"
  nft list ruleset 2>/dev/null | grep -q tailscale0'
graphql "$(jq -cn '{query:"query { numberUsers healthCheck }"}')" "${AUTH_HEADER[@]}" | jq -e '.data.numberUsers >= 1 and .data.healthCheck >= 1 and ((.errors // []) | length == 0)' >/dev/null
open_url "http://$(router_host)/"
open_url "http://$(router_host):2023/"

DAED_PASSWORD=""
DAED_SUBSCRIPTION=""
DAED_TOKEN=""
finish
